"""Add GeneralKnowledge table

Revision ID: 955a99b091c9
Revises: b35052ef50ec
Create Date: 2026-02-02 02:03:30.059070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955a99b091c9'
down_revision: Union[str, None] = 'b35052ef50ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_knowledge_category'), 'general_knowledge', ['category'], unique=False)
    op.create_index(op.f('ix_general_knowledge_id'), 'general_knowledge', ['id'], unique=False)
    op.create_index(op.f('ix_general_knowledge_title'), 'general_knowledge', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_general_knowledge_title'), table_name='general_knowledge')
    op.drop_index(op.f('ix_general_knowledge_id'), table_name='general_knowledge')
    op.drop_index(op.f('ix_general_knowledge_category'), table_name='general_knowledge')
    op.drop_table('general_knowledge')
    # ### end Alembic commands ###
