"""Add sync_status to Disease

Revision ID: b35052ef50ec
Revises: 2cb068dcd17b
Create Date: 2026-02-02 01:47:29.925413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35052ef50ec'
down_revision: Union[str, None] = '2cb068dcd17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('sync_status', sa.String(), nullable=True))
    op.add_column('diseases', sa.Column('sync_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diseases', 'sync_error')
    op.drop_column('diseases', 'sync_status')
    # ### end Alembic commands ###
